version: '3.8'

services:
  backend:
    build: 'backend/'
    environment:
      - PORT=${BACK_PORT}
    ports:
      - '${BACK_PORT}:${BACK_PORT}'
    restart: always
    depends_on:
      - database
      - supervisor
      - riot

  supervisor:
    build: 'services/supervisor/'
    environment:
      - PORT=${SUPERVISOR_PORT}
    ports:
      - '${SUPERVISOR_PORT}:${SUPERVISOR_PORT}'
    restart: always
    depends_on:
      - riot

  riot:
    build: 'services/riot/'
    environment:
      - PORT=${RIOT_PORT}
    ports:
      - '${RIOT_PORT}:${RIOT_PORT}'
    restart: always

  database:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${DB_PORT}:5432'
    restart: always

