name: Compilation Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd backend && yarn install
#          cd frontend && yarn install
#          cd mobile && yarn install
      - name: Check compilation
        run: | 
          cd backend && yarn build
#          cd frontend && yarn build
#          cd mobile && yarn build

