name: Lint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd backend && yarn install
#          cd frontend && yarn install
#          cd mobile && yarn install
      - name: Run linter
        run: | 
          cd backend && yarn lint
#          cd frontend && yarn lint
#          cd mobile && yarn lint
